name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-release:
    name: Build and release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: alist-web
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: |
          cd alist-web
          pnpm install
          pnpm i18n:build
          pnpm build
          cd ..

      - name: Compress build output
        run: |
          cd alist-web
          tar -czvf ../dist.tar.gz dist

      - name: Upload dist.tar.gz
        uses: softprops/action-gh-release@v2
        with:
          tag_name: beta
          name: "Beta Build (from main branch)"
          body: |
            Automated build from push to main branch.
            Commit: ${{ github.sha }}
            Timestamp: ${{ github.event.head_commit.timestamp }}
          prerelease: true
          files: dist.tar.gz
