name: release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: alist-web
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Build
        run: |
          cd alist-web
          version=$(git describe --abbrev=0 --tags)
          sed -i -e "s/\"version\": \"0.0.0\"/\"version\": \"$version\"/g" package.json
          cat package.json
          pnpm install
          pnpm i18n:build
          pnpm build
          cd ..

      - name: Compress build output
        run: |
          cd alist-web
          tar -czvf ../dist.tar.gz dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist.tar.gz
